Реализация требований
ShukinDmitriy/gophermart pull request #1
Opened 2024-06-25 21:39 UTC by ShukinDmitriy

2024-06-30 07:17 UTC, Bazys requested changes
1. Не увидел обработку 429 ошибки. Сейчас по твоей логике ты просто заДДосишь черный ящик. Проект учебный, но в нем учим проавильному обращению со внешними системами в т.ч.
2. Нет ни одного теста. давай доведем покрытие хотя бы до 40%
3. есть несколько вопросов по коду

2024-06-30 07:17 UTC, Bazys commented on cmd/gophermart/main.go
> +		NewClaimsFunc: func(c echo.Context) jwt.Claims {
Параметр функции, названный `c`, не используется в теле функции. В Go, если определили параметр в функции, но не использовали его внутри, это считается неоптимальным стилем, поскольку параметр занимает место в сигнатуре функции и может сбивать с толку при чтении кода.
В данном случае, есть два возможных решения:
1. **Удаление параметра:** Если параметр `c` действительно не нужен для работы функции, его можно просто удалить из сигнатуры функции. Это делает код чище и проще для понимания.
2. **Переименование в `_`:** Если параметр не используется, но его наличие обязательно по какой-то причине (например, для соответствия интерфейсу или для использования в будущем), его можно переименовать в `_`. В Go, символ `_` используется для игнорирования переменной. Переменные, именованные как `_`, не обязаны быть использованы, т.е. не будет копирования неиспользуемого значения внутрь функции. Это позволяет сохранить сигнатуру функции неизменной, но явно указывает на то, что данный параметр в настоящее время не используется и избежать лишнего использования памяти.

2024-06-30 07:17 UTC, Bazys commented on internal/controllers/order.go
> +			} else {
Использование `else` после `return` в блоке `if` избыточно. Потому что если условие в `if` истинно, функция завершится и вернёт значение на этом этапе, и выполнение кода дальше не пойдет. Это значит, что все, что находится в `else`, будет выполнено только если условие `if` не истинно, и нет нужды явно оборачивать этот код в `else`. Таким образом, код становится проще и уменьшается его вложенность, что облегчает его чтение и понимание. Поэтому вместо твоего варианта типа:
```go
if условие {
    return что-то
} else {
    // другой код
}
```
Можно написать кратко:
```go
if условие {
    return что-то
}
// другой код
```
Доп. ссылки:
1. [Effective Go](https://go.dev/doc/effective_go#if)
2. [Uber Go Style Guide](https://github.com/uber-go/guide/blob/master/style.md#reduce-nesting)
3. [Code Health: Reduce Nesting, Reduce Complexity ](https://testing.googleblog.com/2017/06/code-health-reduce-nesting-reduce.html)

2024-06-30 07:17 UTC, Bazys commented on internal/auth/auth.go
> +	"github.com/ShukinDmitriy/gophermart/internal/models"
импорты не отсортированы

2024-06-30 07:17 UTC, Bazys commented on internal/models/get-orders-response.go
> +	stamp := fmt.Sprintf("\"%s\"", time.Time(t).Format(time.RFC3339))
есть метод `sprintfQuotedString`

2024-06-30 07:17 UTC, Bazys commented on cmd/gophermart/main.go
> +func init() {
Функция `init()` в часто считается плохой практикой по нескольким причинам:
1. **Неявные зависимости**: Функции `init()` выполняются автоматически при импорте пакета, что может привести к неявным зависимостям, которые не очевидны из сигнатур функций. Это может затруднить понимание и сопровождение кода.
2. **Неконтролируемый порядок выполнения**: если в пакете имеется несколько функций `init()`, то порядок их выполнения не контролируется программистом в явном виде. Это может привести к непредсказуемому поведению, если функции имеют побочные эффекты, зависящие друг от друга.
3. **Трудности при тестировании**: Функции `init()` запускаются раньше любого другого кода, что может затруднить тестирование. Вы не можете контролировать, когда и выполняется ли функция `init()` в ваших тестах, что может затруднить создание определенных условий для тестирования.
4. **Проблемы производительности**: если функция `init()` выполняет большой объем работы, она может замедлить время запуска программы. Это может стать проблемой для программ, которым требуется быстрый запуск, например, для инструментов командной строки.
5. **Глобальное состояние**: Функции `init()` часто используются для установки глобального состояния, что может привести к проблемам с параллелизмом и сделать код более сложным для понимания.
Вместо использования `init()` часто лучше использовать явные функции инициализации, которые вызываются из `main()` или из функции, которой необходимо инициализированное состояние. Это позволяет четко определить зависимости и порядок выполнения, а также контролировать, когда и как происходит инициализация.
------
1. [Go: функция init](https://medium.com/golangspec/init-functions-in-go-eac191b3860a) - статья на Medium, в которой подробно рассматривается функция `init()` в Go.
2. [Go: Best Practices for Industrial Programming](https://peter.bourgon.org/go-best-practices-2016/#avoid-global-variables) - Руководство по лучшей практике программирования на Go, в котором рекомендуется избегать глобальных переменных и функций `init()`.

2024-06-30 07:17 UTC, Bazys commented on internal/auth/auth.go
> +	claims := u.Claims.(*Claims)
а вдруг там лежит совсем не `*Claims`
всегда проверяй через ok

2024-06-30 07:17 UTC, Bazys commented on internal/services/accrual-service.go
> +	request, err := http.NewRequest(http.MethodGet, url, nil)
```suggestion
	request, err := http.NewRequest(http.MethodGet, url, http.NoBody)
```

2024-07-01 19:07 UTC, ShukinDmitriy commented on internal/auth/auth.go
> +	"github.com/ShukinDmitriy/gophermart/internal/models"
не понял в каком месте конкретно, т.к. ide сама все сортирует и я даже не думаю об этом. в указанном файле попробовал поменять местами импорты - сразу вылезло предложение отсортировать их и IDE вернула прежний порядок

2024-07-01 19:13 UTC, ShukinDmitriy commented on cmd/gophermart/main.go
> +		NewClaimsFunc: func(c echo.Context) jwt.Claims {
Заменил на _ т.к. описан интерфейс данной функции

2024-07-01 19:13 UTC, ShukinDmitriy commented on internal/controllers/order.go
> +			} else {
удалил else

2024-07-01 19:14 UTC, ShukinDmitriy commented on internal/models/get-orders-response.go
> +	stamp := fmt.Sprintf("\"%s\"", time.Time(t).Format(time.RFC3339))
заменил на использование `%q` если оно имелось ввиду

2024-07-01 19:14 UTC, ShukinDmitriy commented on cmd/gophermart/main.go
> +func init() {
Пример брал в документации к библиотеке. переименовал функцию и сделал явный вызов

2024-07-01 19:15 UTC, ShukinDmitriy commented on internal/auth/auth.go
> +	claims := u.Claims.(*Claims)
добавил проверку на ok

2024-07-01 21:00 UTC, ShukinDmitriy commented
> 2\. Нет ни одного теста. давай доведем покрытие хотя бы до 40%

Привет! вопрос по поводу тестов. с юнит тестами понятно: берем функцию, берем ожидаемые значения и проверяем. но как быть с репозиториями и контроллерами, которые составляют основную часть проекта? как быть с сервисом, который должен отправлять запросы во вне? мне кажется не совсем корректно поднимать всю инфраструктуру проекта в контейнерах и проверять результаты, как это сделано в автотестах на гите. какие удобные инструменты замокать есть? Приведу пример из фронтенда, а в частности angular. там у тебя все создается через DI и для всего ты можешь определить callback на вызов того или иного метода замоканного объекта, а после проверить был ли вызван метод и сколько раз. go же вроде как славится своей "простотой" и я неоднократно встречал мнение, что DI это ненужный оверхед для go и нужно создавать все руками. по итогу же я имею велосипед в виде контейнера application, циклические зависимости, если пробую доставать все и везде из контейнера и непонятки с тестированием

2024-07-05 09:44 UTC, Bazys requested changes
насчет тестов все верно, для этого я всегда и говорю что надо в го применять DI и желательно пользовать подходы чистой архитектуры, что бы в дальнейшем ты мог замогать те же сторы и другие сервисы и не вызывать реальные их экземпляры.
https://github.com/vektra/mockery - есть удобный генератор моков.
Во второй половине курса, одним из главных требований, будет поднятие уровня покрытия тестами до 65%
Еще парочка вопросов, главное - избавится от глобальной переменной/

2024-07-05 09:44 UTC, Bazys commented on internal/auth/auth-service.go
> +	"github.com/ShukinDmitriy/gophermart/internal/models"
импорты должны быть отсортированы в следующей последовательности
1. stdlib
2. сторонние библиотеки
3. твои модули

подключи goimports или даже gofumpt на сохранение или на гит-хук при коммите и не надо каждый раз настраивать ИДЕ

2024-07-05 09:44 UTC, Bazys commented on internal/auth/auth-service.go
> +	u := c.Get("user").(*jwt.Token)
а тут проверить? вдруг там не токен лежит?

2024-07-05 09:44 UTC, Bazys commented on internal/application/application.go
> +var App *Application
а она точно должна быть глобалной переменной? почему бы ее не объявить внутри main

2024-07-05 12:35 UTC, ShukinDmitriy commented on internal/application/application.go
> +var App *Application
убрал этот велосипед и использовал fx

2024-07-05 12:35 UTC, ShukinDmitriy commented on internal/auth/auth-service.go
> +	u := c.Get("user").(*jwt.Token)
добавил проверку.

2024-07-05 12:36 UTC, ShukinDmitriy commented on internal/auth/auth-service.go
> +	"github.com/ShukinDmitriy/gophermart/internal/models"
добавил husky для запуска хуков и внутри на pre-commit подключил gofumpt

2024-07-07 19:17 UTC, Bazys approved these changes
go.uber.org/fx - немного из пушки по воробьям в нашем случае, но пока пусть так, в дальнейшем думаю сам справишься.

2024-07-08 05:51 UTC, merged